from __future__ import annotations

"""Cleanup of files owned by a previous Analyze run."""

from copy import deepcopy
from pathlib import Path
import shutil
from typing import Any, Mapping

from .render import RenderSession
from .reporting import clear_previous_summary_outputs
from .reporting.csv_writer import remove_summary_csvs, remove_summary_detail_csvs


def cleanup_previous_analyze_outputs(
    outdir: Path,
    config: Mapping[str, Any],
    *,
    grouped_roots: bool = True,
) -> None:
    """Remove known generated outputs without touching unrelated user files."""
    root = Path(outdir)
    child_roots = (
        [
            root / f"result_{label}"
            for label in "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
            if (root / f"result_{label}").is_dir()
        ]
        if grouped_roots
        else []
    )
    for candidate in [*child_roots, root]:
        cleanup_generated_output_root(candidate, config)
    for candidate in child_roots:
        remove_empty_tree(candidate)


def cleanup_generated_output_root(
    root: Path,
    config: Mapping[str, Any],
) -> None:
    """Remove only files and empty directories generated by SQQ."""
    path = Path(root)
    if not path.exists():
        return
    mutable_config = deepcopy(dict(config))
    RenderSession.cleanup_output(path)
    clear_previous_summary_outputs(path, mutable_config)
    for name in (
        "summary.xlsx",
        "summary.md",
        "sqq_config_resolved.yaml",
        "run_config.yaml",
    ):
        (path / name).unlink(missing_ok=True)
    remove_summary_csvs(path, mutable_config)
    legacy_config = deepcopy(mutable_config)
    legacy_config.setdefault("output", {})["summary_csv_dir"] = "summary_csv"
    remove_summary_csvs(path, legacy_config)
    remove_summary_detail_csvs(path, mutable_config)
    shutil.rmtree(path / "track", ignore_errors=True)

    report_suffixes = (
        "_info.md",
        "_membership.tsv",
        "_order_parameter.tsv",
        "_f3f4.tsv",
        "_view.vmd.tcl",
    )
    gro_markers = (
        "_ring_",
        "_hc_",
        "_half_cage",
        "_qc_",
        "_quasi_cage",
        "_cage_",
        "_ice",
        "_cluster_",
        "_f3.gro",
        "_f4.gro",
    )
    generated_gro_dirs = {
        "ring",
        "half_cage",
        "quasi_cage",
        "cage",
        "hydrate_cluster",
        "ice",
        "order",
    }
    for candidate in path.rglob("*"):
        if not candidate.is_file():
            continue
        name = candidate.name.casefold()
        if name.endswith(report_suffixes):
            candidate.unlink(missing_ok=True)
        elif name.endswith(".gro"):
            relative_parts = {
                part.casefold() for part in candidate.relative_to(path).parts[:-1]
            }
            if any(marker in name for marker in gro_markers) or (
                relative_parts & generated_gro_dirs
            ):
                candidate.unlink(missing_ok=True)
    remove_empty_tree(path, keep_root=True)


def remove_empty_tree(root: Path, *, keep_root: bool = False) -> None:
    """Remove empty descendants and optionally the empty root."""
    path = Path(root)
    if not path.exists():
        return
    directories = sorted(
        (item for item in path.rglob("*") if item.is_dir()),
        key=lambda item: len(item.parts),
        reverse=True,
    )
    for directory in directories:
        try:
            directory.rmdir()
        except OSError:
            pass
    if not keep_root:
        try:
            path.rmdir()
        except OSError:
            pass


__all__ = [
    "cleanup_generated_output_root",
    "cleanup_previous_analyze_outputs",
    "remove_empty_tree",
]
